# Unfortunatly since we still want access to the manifest, the app fundle etc. we cannot use '/*'
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true # Ensure that we always redirect
[[redirects]]
  from = "/register"
  to = "/index.html"
  status = 200
  force = true # Ensure that we always redirect
